// Enemy projectiles: HDE visuals, Halo CE impact damage
class HCE_ARBullet : HaloMAB_Bullet
{
	mixin HCE_NerfMixin;
	Default
	{
		HaloProjectile.BaseDamage 10;
	}
}

class HCE_BattleRifleARBullet : HaloBattleRifle_Bullet
{
	mixin HCE_NerfMixin;
	Default
	{
		HaloProjectile.BaseDamage 12;
	}
}

class HCE_H2BeamShot : HCE_BeamPuff
{
	Default
	{
	}
}

class HCE_BulldogBuckshot : HaloBulldog_Bullet
{
	mixin HCE_NerfMixin;
	Default
	{
		HaloProjectile.BaseDamage 7;
	}
}

class HCE_CommandoARBullet : HaloCommando_Bullet
{
	mixin HCE_NerfMixin;
	Default
	{
		HaloProjectile.BaseDamage 14;
	}
}

class HCE_DMRSniperBullet : HaloDMR_Bullet
{
	mixin HCE_NerfMixin;
	Default
	{
		HaloProjectile.BaseDamage 24;
	}
}

class HCE_DBLShotgunPellet : HaloDBLShotgun_Bullet
{
	mixin HCE_NerfMixin;
	Default
	{
		HaloProjectile.BaseDamage 9;
	}
}

class HCE_Flame : HaloFlames
{
	Default
	{
	}
}

class HCE_FuelRodBolt : HCE_FuelRodScaled
{
	Default
	{
	}
}

class HCE_GPMGBullet : HaloGPMG_Bullet
{
	mixin HCE_NerfMixin;
	Default
	{
		HaloProjectile.BaseDamage 15;
	}
}

class HCE_40mmGrenade : Halo_40MM_Proj
{
	Default
	{
	}
}

class HCE_HydraMissile : HydraMissile
{
	Default
	{
	}
}

class HCE_MA37Round : HaloRifle_Bullet
{
	mixin HCE_NerfMixin;
	Default
	{
		HaloProjectile.BaseDamage 9;
	}
}

class HCE_Needle : HCE_NeedleScaled
{
	Default
	{
	}
}

class HCE_PistolBullet : HaloSidekick_Bullet
{
	mixin HCE_NerfMixin;
	Default
	{
		HaloProjectile.BaseDamage 25;
	}
}

class HCE_PlasmaCasterGrenade : HCE_PlasmaCasterScaled
{
	Default
	{
	}
}

class HCE_PlasmaPistolBolt : HaloPlasma_Proj
{
	mixin HCE_NerfMixin;
	Default
	{
		HaloProjectile.BaseDamage 18;
	}
}

class HCE_PlasmaRifleBolt : HaloPlasmaRifle_Proj
{
	mixin HCE_NerfMixin;
	Default
	{
		HaloProjectile.BaseDamage 13;
	}
}

class HCE_Rocket : HCE_RocketScaled
{
	Default
	{
	}
}

class HCE_ShotgunPellet : HaloShotgun_Bullet
{
	mixin HCE_NerfMixin;
	Default
	{
		HaloProjectile.BaseDamage 20;
	}
}

class HCE_SidekickRound : HaloSidekick_Bullet
{
	mixin HCE_NerfMixin;
	Default
	{
		HaloProjectile.BaseDamage 18;
	}
}

class HCE_SMGRound : HaloSMG_Bullet
{
	mixin HCE_NerfMixin;
	Default
	{
		HaloProjectile.BaseDamage 6;
	}
}

class HCE_SniperBullet : HaloSniper_Bullet
{
	mixin HCE_NerfMixin;
	Default
	{
		HaloProjectile.BaseDamage 101;
	}
}

class HCE_StanchionRail : HaloSniper_Bullet
{
	mixin HCE_NerfMixin;
	Default
	{
		HaloProjectile.BaseDamage 150;
	}
}

class HCE_StickyDetCharge : HaloStickyDetProj
{
	Default
	{
	}
}

class HCE_ChargedPlasma : HaloChargedPlasma_Proj
{
	mixin HCE_NerfMixin;
	Default
	{
		HaloProjectile.BaseDamage 70;
	}
}
